name: onesystem_bloc
description: OneSYSTEM.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  animations: ^2.0.2
  auto_route: ^3.2.4
  auto_size_text: ^3.0.0
  cached_network_image: ^3.2.0
  card_swiper: ^2.0.3
  cupertino_icons: ^1.0.2
  dio: ^4.0.6
  easy_localization: ^3.0.0
  equatable: ^2.0.3
  firebase_analytics: any
  firebase_core: ^1.14.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.1
  flutter_rating_bar: ^4.0.0
  flutter_svg: ^1.0.3
  lottie: ^1.2.2
  provider: ^6.0.2
  shared_preferences: ^2.0.13
  shimmer: ^2.0.0

dev_dependencies:
  auto_route_generator: ^3.2.3
  build_runner: ^2.1.8
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/lang/
    - assets/svg/
    - assets/images/
    - assets/lotties/
